### ISSUE TITLE
How to setup parameters like num_beams, temperature, top_p, top_k during inference?

### ISSUE THREAD

**Issue by rbhatia46** [stochasticai/xturing#101]
Hi,
Great work toward democratising LLMs, I do have a quick question, how do I pass parameters like temperature, top_p, top_k etc when making predictions once the model training is complete and I call **model.generate()** ? Any help is appreciated.

Thanks & Regards,
Rahul

**Comment by StochasticRomanAgeev** [comment]
Hi @rbhatia46 ,

model.generation_config()

Will return you an instance of GenerationConfig class, which you can modify, and changes will reflect on generation process
(.top_p is top_p, .top_k is top_k)
