### ISSUE TITLE
Unable to install xturing 0.0.7 in Google Colab

### ISSUE THREAD

**Issue by datorresb** [stochasticai/xturing#102]
I am trying to install the latest version of xturing (0.0.7) in Google Colab using the following command:

`!pip install git+https://github.com/stochasticai/xturing.git install 0.0.7`

However, the installation process does not complete and hangs indefinitely. In contrast, the previous stable release (0.0.5) installs without any issues using the command:

`!pip install xturing==0.0.5`

The error message I get during the installation of version 0.0.7 is related to the textract package and specifically the python setup.py egg_info command, which fails to run successfully. Here is the full error message:

```
Collecting extract-msg<=0.29.*
  Downloading extract_msg-0.28.7-py2.py3-none-any.whl (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.0/69.0 KB 10.0 MB/s eta 0:00:00
Collecting textract
  Downloading textract-1.6.4.tar.gz (17 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Any suggestions on how to fix this issue and successfully install version 0.0.7 of xturing in Google Colab would be greatly appreciated. Thank you.

**Comment by StochasticRomanAgeev** [comment]
Hi, @datorresb 

You should use the same command but with 0.0.7 version.
```bash
!pip install xturing==0.0.7
```
