### ISSUE TITLE
Setting the temperature parameter

### ISSUE THREAD

**Issue by alashraf01** [stochasticai/xturing#107]
model.generate() - how i can set temperature parameter before generation?

**Comment by Toan-Do** [comment]
Hi @alashraf01 ,

Currently we support top-p sampling (top_k, top_p, max_new_tokens) and contrastive search (penalty_alpha, top_k, max_new_tokens) techniques in generation method. We will add other parameters like temerature soon. You can change these parameter using below code or checkout our [documentation](https://xturing.stochastic.ai/inference/configure):

```
generation_config = model.generation_config()
generation_config.top_k = 10
```
