### ISSUE TITLE
ImportError: cannot import name 'Literal' from 'typing' (/opt/conda/lib/python3.7/typing.py)

### ISSUE THREAD

**Issue by jatintyagi7** [stochasticai/xturing#115]
For python version <3.8, Literal import is creating and issue in text_splitter.py

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_23/446338945.py in <module>
----> 1 from xturing.datasets.instruction_dataset import InstructionDataset
      2 from xturing.models import BaseModel
      3 

/opt/conda/lib/python3.7/site-packages/xturing/__init__.py in <module>
      3 configure_external_loggers()
      4 
----> 5 from .datasets import BaseDataset, InstructionDataset, TextDataset
      6 from .engines import (
      7     BaseEngine,

/opt/conda/lib/python3.7/site-packages/xturing/datasets/__init__.py in <module>
      1 from .base import BaseDataset
----> 2 from .instruction_dataset import InstructionDataset, InstructionDatasetMeta
      3 from .text2image_dataset import Text2ImageDataset
      4 from .text_dataset import TextDataset, TextDatasetMeta
      5 

/opt/conda/lib/python3.7/site-packages/xturing/datasets/instruction_dataset.py in <module>
     11 from xturing.datasets.base import BaseDataset
     12 from xturing.model_apis import TextGenerationAPI
---> 13 from xturing.self_instruct import (
     14     bootstrap_instructions,
     15     generate_instances,

/opt/conda/lib/python3.7/site-packages/xturing/self_instruct/prepare_seed_tasks.py in <module>
      7 
      8 from xturing.model_apis import TextGenerationAPI
----> 9 from xturing.utils.text_splitter import RecursiveCharacterTextSplitter
     10 
     11 

/opt/conda/lib/python3.7/site-packages/xturing/utils/text_splitter.py in <module>
      6 import logging
      7 from abc import ABC, abstractmethod
----> 8 from typing import (
      9     AbstractSet,
     10     Any,

**Comment by Toan-Do** [comment]
Hi @jatintyagi7,

Thank you for rasing it. In the meantime, could you upgrade Python to 3.8 or 3.9 and try again? xTuring should work with python>=3.8.

**Comment by jatintyagi7** [comment]
Hi I am trying this in kaggle notebook, not sure whether the python upgrade is feasible there or not

**Comment by jatintyagi7** [comment]
@Toan-Do there is one solution which will make it work: 
please replace the 
from typing import Literal

with 

try:
    from typing import Literal
except ImportError:
    from typing_extensions import Literal
