### ISSUE TITLE
TPU Support

### ISSUE THREAD

**Issue by Bobberson3108** [stochasticai/xturing#123]
I have got access to the Google Cloud TPU Research grant and would like to use xturing with it. Could you add TPU support to the library?

**Comment by StochasticRomanAgeev** [comment]
Hi @Bobberson3108,

Libraries we are using have support of TPUs, but we need some time to test this. You can also try to add the flag to the training yourself, we will be grateful for any help!

**Comment by PsuedoJack** [comment]
> I have got access to the Google Cloud TPU Research grant and would like to use xturing with it. Could you add TPU support to the library?

I will tell you love to try  send me what you need and build stable one. You have grant for research?Scientists, Create

**Comment by StochasticRomanAgeev** [comment]
Hi @Bobberson3108 
You can check Trainer code, if pytorch lightning TPU support will work for you then it is the only place
