### ISSUE TITLE
M1 Mac support

### ISSUE THREAD

**Issue by raviteja5** [stochasticai/xturing#124]
Thanks for your efforts in making this library. I have a M1 mac, and it says CUDA is not available.

Do you support acceleration on Mac with Metal (MPS) etc.? 

Thanks!

**Comment by StochasticRomanAgeev** [comment]
Hi @raviteja5 , M1 is supported in cpu mode, for distilgpt2_lora model it should work good (~270Mb), you can also use gpt2_lora (~1GB) and gpt2 (~3.5GB)
We are also doing experiments to support M1 gpu mode to get speedup, but it is working only in pytorch dev build

**Comment by PsuedoJack** [comment]
Great
