### ISSUE TITLE
Ability to train using negative datasets

### ISSUE THREAD

**Issue by rakovskij-stanislav** [stochasticai/xturing#127]
Feature: Train models using datasets with "do not answer this way" / irrelevant flag (e.g. for avoiding low-quality answers or answers like "as AI model", "I have no practical experience..." and other biases of openai-like answers).

Example of dataset with bad answers discrimination: https://huggingface.co/datasets/Den4ikAI/russian_dialogues

**Comment by rakovskij-stanislav** [comment]
Another example with quality discrimination: https://huggingface.co/datasets/IlyaGusev/ru_turbo_alpaca

**Comment by StochasticRomanAgeev** [comment]
Hi @rakovskij-stanislav, 
For avoiding some generation patterns you can use `bad_words_ids` parameter.

**Comment by rakovskij-stanislav** [comment]
@StochasticRomanAgeev thanks, it mets my tasks for now)
