### ISSUE TITLE
Documentation needs a lot of work

### ISSUE THREAD

**Issue by MillionthOdin16** [stochasticai/xturing#132]
The readme for this project shows some pretty cool stuff and makes it look super simple to get going.

In reality, a lot of the documentation is half baked and you need better integration between all of your examples. It doesn't really make sense that there's so many different example notebooks for very slight variations like whether it's 8-bit or not. It would be much more straightforward to understand if notebooks were integrated together.

In addition to the above, I tried to load existing models that I have locally and it seems to want to download your own model files, or complains that the hub isn't prefixed with '/x'. A lot of these files are large, really frustrating that I'm forced to download them from your servers.

Beyond this, the whole reason I was looking at this repo is because it claims to do 4bit lora training. The 4 bit example is very confusing because you have a notebook for Python. It's basically just setting up a docker image. No discussion of how the 4-bit training is done, nothing about which models it's capable of working with, and it's basically a black box.

I'm also getting messages about a mismatch between the version of the llama tokenizer, which I would expect would be resolved if you're hosting the models that users download.

So while the project documentation implies that the library is basically ready to go after a pip install, this isn't really the reality and it seems like examples were just thrown together by different people in order to say that ' there's an example for that'.

**Comment by sarthaklangde** [comment]
@MillionthOdin16 I agree with you. Initially, we started with just simple fine-tuning and it quickly snowballed into many variants of fine-tuning. We should simplify this for sure.

It is quite strange that you were not able to load your models from disk (I am assuming you were trying to do this). Could you shed more light on this? What weights did you have on your local disk?

About the 4-bit fine-tuning, we are still working on getting it integrated into the xTuring library. We just wanted to showcase that it is quite possible. The docker container is able to perform INT4 fine-tuning using modified versions of popular libraries. We are trying to integrate this ASAP into xTuring source and you should have it working in a day or two.

Most of the suggestions here are very good, would you like to fix them?

**Comment by glennko** [comment]
We now have updated the code to provide int4 fine-tuning without the docker image.
