### ISSUE TITLE
the label mask of InstructionDataCollator is not right

### ISSUE THREAD

**Issue by Mousaic** [stochasticai/xturing#139]
the label mask of InstructionDataCollator is not right

**Comment by Mousaic** [comment]
label mask should roll -1 too

**Comment by Toan-Do** [comment]
Hi @Mousaic ,

The mask in InstructionDataCollator is correct. It applies to the [loss calculation](https://github.com/stochasticai/xturing/blob/main/src/xturing/utils/loss_fns.py#L15)

**Comment by Mousaic** [comment]
label_mask =[False] * len(input_instruction["input_ids"])+
                      [False] * len(input_text["input_ids"])+ 
                      [True] * len(input_target["input_ids"])
should we change label_mask to  
label_mask =[False] * len(input_instruction["input_ids"]-1)+ 
                    [False] * len(input_text["input_ids"])+ 
                    [True] * len(input_target["input_ids"]) + [False].

**Comment by Mousaic** [comment]
@Toan-Do

**Comment by StochasticRomanAgeev** [comment]
Hi @Mousaic,

What do you mean by "label mask should roll -1 too"?

Thanks for helping us with issue!
