### ISSUE TITLE
CUDA memory error with LLaMA and GPT-J

### ISSUE THREAD

**Issue by peter-ch** [stochasticai/xturing#140]
I'm running fine-tuning on the Alpaca dataset with llama_lora_int8 and gptj_lora_int8, and training works fine, but when it completes an epoch and attempts to save a checkpoint I get this error: 

OutOfMemoryError: CUDA out of memory. Tried to allocate 44.00 MiB (GPU 0; 10.75 GiB total capacity; 9.40 GiB already allocated; 58.62 MiB free; 9.76 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

But the GPU is RTX2080Ti with 11GBs of VRAM and the training works. Isn't that enough VRAM? I can't even get the state_dict with model.engine.state_dict(), I get the same error.

**Comment by Toan-Do** [comment]
Hi @peter-ch ,

You can decrease the batch size when fine-tuning to reduce GPU usage. The default batch size for LoRA INT8 is 8 which could be quite high in your case. You can check out [our document][https://xturing.stochastic.ai/finetune/configure] to see how to do it.
