### ISSUE TITLE
'GPTJInt8Engine' object has no attribute 'tokenizer'

### ISSUE THREAD

**Issue by eksis77** [stochasticai/xturing#142]
engines/gptj_engine.py 53 line 

tokenizer.pad_token = self.tokenizer.eos_token

"self" does not have tokenizer...

tokenizer.pad_token = tokenizer.eos_token 
is right??

**Comment by Toan-Do** [comment]
Hi @eksis77 ,

You are correct. Thank you for raising it. Feel free to make a PR. Otherwise we will fix it in the next release.

**Comment by Toan-Do** [comment]
#146

**Comment by Toan-Do** [comment]
Fixed in #146
