### ISSUE TITLE
What steps to take to add GPT-NeoX model?

### ISSUE THREAD

**Issue by peter-sk** [stochasticai/xturing#150]
Hi,
I'd like to add GPT-NeoX support. Any pointers what I would need to do for that?
Cheers,
Peter

**Comment by sarthaklangde** [comment]
Hey @peter-sk,

Thank you for reaching out. We do have a guide here:
[https://xturing.stochastic.ai/contributing/model_contributing](https://xturing.stochastic.ai/contributing/model_contributing
)

If you need more help or clarification, let me know.
