### ISSUE TITLE
How to increase epoch for training and  build xturing  from source code ?

### ISSUE THREAD

**Issue by sazzad15-1779** [stochasticai/xturing#151]
i was trying to finetune cerebras 1.3b model with alpaca dataset in bengali. At first i run  [cerebras_lora.ipynb] with this dataset. it execute only for 3 epochs which gave poor output. for that reason im searching how to increase epoch .
second question is  any way to build xturing?

**Comment by Toan-Do** [comment]
Hi @sazzad15-1779 ,

You can check [our document](https://xturing.stochastic.ai/finetune/configure) to see how to increase the number of epochs.
