### ISSUE TITLE
Getting error with llama_lora_int8

### ISSUE THREAD

**Issue by royrajjyoti1** [stochasticai/xturing#163]
<img width="1177" alt="Sc" src="https://user-images.githubusercontent.com/89331521/233936278-e8837aeb-dacc-439d-b5eb-6ffb4b1d64d7.png">

**Comment by brijeshKarna** [comment]
Having same issue @sarthaklangde

**Comment by royrajjyoti1** [comment]
Thank you @Toan-Do  now its working for me. 😀
