### ISSUE TITLE
Integrated GPU w/ Dedicated GPU

### ISSUE THREAD

**Issue by TonySCruze** [stochasticai/xTuring#164]
So my laptop has 

7.9 GB shared graphics memory 
6 GB of Dedicated Graphics memory (Nvidia)
= 13.9 GB of GPU memory

16GB of System memory (RAM)

When I run the llama_lora_int4 example https://github.com/stochasticai/xturing/blob/main/examples/int4_finetuning/LLaMA_lora_int4.ipynb

Expected : 
finetuning to complete and a few randomly predicted words from the newly tuned LM appear in the terminal 

Actual: 
I keep running into the following cuda out of memory error

tensor_to_reduce = tensor.to(self.communication_data_type)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 764.00 MiB (GPU 0; 6.00 GiB total capacity; 4.57 GiB already allocated; 0 bytes free; 4.89 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

1. How do I get this to use all of my GPU memory. 
2. why does running this example fill up my CPU memory instead of GPU memory? (I can see the GPU is being engaged but it's not filling memory like the CPU ram is being filled up to capacity)
3. can I use both GPUs to help the process

UPDATE: I just realize my integrated graphics is Intel. This could make using both simultaneously impossible, as I believe that pytorch only work with CUDA (nvidia). Any guidace from other users trying this would help. or this can be closed as this is not an actual issue of this framework.

**Comment by StochasticRomanAgeev** [comment]
Hi @TonySCruze,
This int4 feature requires NVIDIA card, because we are using custom CUDA kernels there
I hope we will release int4 for any gpu-like devices at some point, but now we are unable to support this
