### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for LoraModel

### ISSUE THREAD

**Issue by brijeshKarna** [stochasticai/xturing#179]
***Environment Spec***
>>>google colab t4 high ram

While running below code 
```
from xturing.models import BaseModel
model = BaseModel.load("x/llama_lora_finetuned_alpaca")
```
got an error 

RuntimeError: Error(s) in loading state_dict for LoraModel:
Missing key(s) in state_dict: "model.model.embed_tokens.weight"
.................
.................
"model.model.layers.31.self_attn.v_proj.weight", "model.model.layers.31.self_attn.v_proj.lora_A.weight", 
"model.model.layers.31.self_attn.v_proj.lora_B.weight", "model.model.layers.31.self_attn.o_proj.weight", 
"model.model.layers.31.self_attn.rotary_emb.inv_freq", "model.model.layers.31.mlp.gate_proj.weight", 
"model.model.layers.31.mlp.down_proj.weight", "model.model.layers.31.mlp.up_proj.weight", 
"model.model.layers.31.input_layernorm.weight", "model.model.layers.31.post_attention_layernorm.weight", 
"model.model.norm.weight", "model.lm_head.weight". 
        Unexpected key(s) in state_dict: "base_model.model.model.embed_tokens.weight", 
..................
..................

@Toan-Do @sarthaklangde

**Comment by StochasticRomanAgeev** [comment]
Hi @brijeshKarna, we were changing weights mappings
Do you use latest version of xturing?
```pip install xturing -U```

**Comment by brijeshKarna** [comment]
> Hi @brijeshKarna, we were changing weights mappings Do you use latest version of xturing? `pip install xturing -U`

got this RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

**Comment by StochasticRomanAgeev** [comment]
Hi @brijeshKarna,
Can you clarify about my latest question?
What version are you using now?

**Comment by brijeshKarna** [comment]
> Hi @brijeshKarna, Can you clarify about my latest question? What version are you using now?

as you mentioned i have used latest version of xturing using "pip install xturing -U"

**Comment by StochasticRomanAgeev** [comment]
Hi, @brijeshKarna 
We will reload and retune model in new format
For now you can use 

```python
from xturing.models import BaseModel
model = BaseModel.load("llama_lora")
```
