### ISSUE TITLE
How to set generate_dataset_from_dir parameters properly for more diverse and more samples?

### ISSUE THREAD

**Issue by Purulence666** [stochasticai/xturing#183]
Hi guys, newbie here. I have a few questions regarding the data generation. I am using "generate_dataset_from_dir" to generate the dataset from a large .xls file consisting few thousands items of product info. Right now I can't set the “use_self_instruct” to True, it's giving me errors. And with default parameter values, it only generates fixed amount of new data samples. for example: for 5 data points in my excel file, it only generates 5 questions. currently my code looks like this:

```
from xturing.datasets import InstructionDataset
from xturing.model_apis.openai import Davinci, ChatGPT

engine = ChatGPT("*************************************************8")
dataset = InstructionDataset.generate_dataset_from_dir(path="data/", 
                                                       engine=engine,
                                                       use_self_instruct=False, 
                                                       chunk_size=8000,
                                                       num_instructions = 10,
                                                       num_instructions_for_finetuning = 5,
                                                       num_prompt_instructions = 1,
                                                       num_samples_per_chunk=5)
dataset.save("./my_generated_dataset") 
[print(i) for i in dataset] # print the generated dataset

````

My questions are as follows:

1. What is the correct way to "set use_self_instruct" to "True" to get more diverse and samples?
2. What do these parameters exactly mean? - num_instructions, num_instructions_for_finetuning, num_prompt_instructions, num_samples_per_chunk.
3. For a dataset containing let's say 2000 items that have info related to its price, brand, type, topic, category, description etc, how many instruct data are enough to fine-tune a LLama 7b model? and how should I set these (num_instructions, num_instructions_for_finetuning, num_prompt_instructions, num_samples_per_chunk) parameters to generate maximum and enough numbers of new samples?

Any useful insight, suggestion is greatly appreciated.

**Comment by Toan-Do** [comment]
Hi @Purulence666 ,

1. What is your error when setting use_self_instruct =True
2. You can check out our documentation to understand these parameters: https://xturing.stochastic.ai/datasets/generate
3. The generate_dataset_from_dir focus on generating question answering data from plain text data. You can use generate_dataset method to generate diverse tasks given the some examples in the seed_tasks.json file
