### ISSUE TITLE
Request for CPU only support 

### ISSUE THREAD

**Issue by chriskuchar** [stochasticai/xturing#193]
I'm trying to run this code on cpu, using version 0.1.3 of xturing. I think because I'm not running GPU it's throwing errors. Could you add support for CPU?

The error I'm getting is "addmm_impl_cpu_" not implemented for 'Half'. I googled it and it says I need to change the data type of operands to float 32 from float 16. https://stackoverflow.com/questions/73530569/pytorch-matmul-runtimeerror-addmm-impl-cpu-not-implemented-for-half

Is this the case here? If so, how do I change it? If not, can I get help so I can run this?

Thanks,
Chris
```
from xturing.datasets import InstructionDataset
from xturing.models import BaseModel

 

import json

from datasets import Dataset, DatasetDict

# Convert the alpaca JSON dataset to HF format


# Right now only the HuggingFace datasets are supported, that's why the JSON Alpaca dataset
# needs to be converted to the HuggingFace format. In addition, this HF dataset should have 3 columns for instruction finetuning: instruction, text and target.
def preprocess_alpaca_json_data(alpaca_dataset_path: str):
    """Creates a dataset given the alpaca JSON dataset. You can download it here: https://raw.githubusercontent.com/tatsu-lab/stanford_alpaca/main/alpaca_data.json
    :param alpaca_dataset_path: path of the Alpaca dataset
    """
    alpaca_data = json.load(open(alpaca_dataset_path))
    instructions = []
    inputs = []
    outputs = []

    for data in alpaca_data:
        instructions.append(data["instruction"])
        inputs.append(data["input"])
        outputs.append(data["output"])

    data_dict = {
        "train": {"instruction": instructions, "text": inputs, "target": outputs}
    }

    dataset = DatasetDict()
    # using your `Dict` object
    for k, v in data_dict.items():
        dataset[k] = Dataset.from_dict(v)

    dataset.save_to_disk(str("./alpaca_data"))


preprocess_alpaca_json_data('alpaca_data.json')
# Load the dataset
instruction_dataset = InstructionDataset("alpaca_data")

# Initialize the model
model = BaseModel.create("llama_lora")
instruction_dataset
# Finetune the model
model.finetune(dataset=instruction_dataset)
```

**Comment by StochasticRomanAgeev** [comment]
Hi, @chriskuchar 
You can use `model = BaseModel.create("llama")`
You also can change value to 32 if you want `llama_lora` [here](https://github.com/stochasticai/xturing/blob/142954bd5ecc4bba6de72c7e6fc45ed4818340a8/src/xturing/engines/causal.py#L149)
We will also appreciate any help provided with this error, here you can find [contribution guide](https://github.com/stochasticai/xturing/blob/main/CONTRIBUTING.md).

**Comment by chriskuchar** [comment]
@StochasticRomanAgeev Thanks for the reply! If I run `model=BaseModel.create("llama") will I still get the ~20 minute training run-time?` Or would it be better for me to just change the value to 32?
