### ISSUE TITLE
Training LlaMa with alpaca data multigpu error

### ISSUE THREAD

**Issue by cmxela** [stochasticai/xTuring#194]
Hello,
I would appreciate some help with an error I am getting.
I am trying to train LlaMa with the alpaca data in a system with Fedora linux 38 with two RTX 3090. 

I am getting the following error message when the training starts...

`
RuntimeError: Lightning can't create new processes if CUDA is already initialized. Did you manually call `torch.cuda.*` functions, have moved the model to the device, or allocated memory on the GPU any other way? Please remove any such calls, or change the selected strategy. You will have to restart the Python kernel.`

issue  #187 says that xturing uses multigpus automatically and issue #171 says that INT8 does not supports multigpu but lora and the original model support multigpu.

If  I set CUDA_VISIBLE_DEVICES to 0 then it starts the training but the estimated time is more than 6 hours for the 3 epochs

**Comment by StochasticRomanAgeev** [comment]
Hi @cmxela, 
You can use original model with bigger batch and 2 GPU-s or INT8 lora model with bigger batch and 1 GPU
