### ISSUE TITLE
Faster Inference/Multiple Batch size during generate/inference?

### ISSUE THREAD

**Issue by rbhatia46** [stochasticai/xturing#195]
Hi,
Is there any way I can speed up the inference procedure or increase the batch_size during inference?

**Comment by StochasticRomanAgeev** [comment]
Hi @rbhatia46,
We will add this option to generation config in next updates
For now you need to edit code [here](https://github.com/stochasticai/xturing/blob/142954bd5ecc4bba6de72c7e6fc45ed4818340a8/src/xturing/models/causal.py#L143)
We will also appreciate any help provided with this error, here you can find [contribution guide](https://github.com/stochasticai/xturing/blob/main/CONTRIBUTING.md).
