### ISSUE TITLE
generate() returns the same output 8 times

### ISSUE THREAD

**Issue by markusdr** [stochasticai/xturing#196]
The following toy code results in the same output printed 8 times when run on a machine with 8 GPUs:

    from xturing.models import BaseModel
    from xturing.datasets.instruction_dataset import InstructionDataset
    data = InstructionDataset({
        "text": ["first text", "second text"],
        "target": ["first text", "second text"],
        "instruction": ["first instruction", "second instruction"]
    })
    model = BaseModel.create("cerebras_lora")
    model.finetune(dataset=data)
    print(model.generate(texts=['Hello, world!'])) # prints 8 identical lines

**Comment by StochasticRomanAgeev** [comment]
Hi @markusdr,
We will edit logging in next updates, for now you can re-define std out to std error or suppress it using `with` python wrapper
We will also appreciate any help provided with this error, here you can find [contribution guide](https://github.com/stochasticai/xturing/blob/main/CONTRIBUTING.md).
