### ISSUE TITLE
logging output appears on stdout

### ISSUE THREAD

**Issue by markusdr** [stochasticai/xturing#197]
xTuring generates lots of logging output on stdout, but it should be on stderr instead. 

Currently, the logging output on stdout gets mixed with the actual output that library users want to print, e.g.,

    print(model.generate(...))

**Comment by StochasticRomanAgeev** [comment]
Hi @markusdr,
We will edit logging in next updates, for now you can re-define std out to std error or suppress it using `with` python wrapper
We will also appreciate any help provided with this error, here you can find [contribution guide](https://github.com/stochasticai/xturing/blob/main/CONTRIBUTING.md).
