### ISSUE TITLE
New models of dataset to use 

### ISSUE THREAD

**Issue by mums77** [stochasticai/xTuring#199]
Hey all, I'm currently running finetuning with the original dataset provided in the example. 

Unfortunately the basic two options which are "Input" and "output" limit the amount of trainable parameters

Is it possible to use other models of dataset or will that be released soon ?

Thanks

**Comment by StochasticRomanAgeev** [comment]
Hi @mums77,
It is LoRa feature, it helps fitting big model to your GPU.
If you want try to finetune full model, use

```python
BaseModel.create("llama_int8")
```

**Comment by mums77** [comment]
Hey @StochasticRomanAgeev  thanks for the anwser

I think I was not clear sorry, I understand that there is many different models that can be used and I appreciate that. 
My concern was more about the finetuning with the dataset, for instance I want to build a prompt answering language model with one of the model but as I understand there is only the huggingface dataset model that is supported for now. 

Unfortunately this dataset is quite limitating as there is only a "Input" and "output" in the dataset. That doesn't make my model really smart as it can roughly answers only the question i've added to the dataset

I was wondering if there is or there will be other dataset type that will be added later ?

As an example another project on github is using the model : "Question" , "assistant hypothetical answer" , "Agent Reflection" , "Assistant final answer" to train the model

That gives nice result as there is in a simple question many different aspect that are covered 

Thanks foe the answer
/M

**Comment by StochasticRomanAgeev** [comment]
Hi again, @mums77 
Out dataset supports prompt templates, but probably you can gust put entire prompt in input column, it is the easy way.
