### ISSUE TITLE
Add MPT-7B

### ISSUE THREAD

**Issue by MohamedAliRashad** [stochasticai/xTuring#204]
I want to finetune MPT-7B instruct on a dataset i created … can you add MPT-7 to the list of models supported ?

**Comment by glennko** [comment]
@MohamedAliRashad If you want to take a stab at writing a piece of code and contributing to the project, refer to this: https://xturing.stochastic.ai/contributing/model_contributing/.

**Comment by StochasticRomanAgeev** [comment]
Hi again, @MohamedAliRashad 
In latest release we added [Generic model](https://github.com/stochasticai/xTuring/tree/main/examples/generic), you can use it for  `MPT-7B` in our library!
Also maybe a good option for you will be `falcon-7b` model, that is now supported by xturing.

**Comment by MohamedAliRashad** [comment]
@StochasticRomanAgeev I was afraid that the project will become idle without any improvement.
Thank you for your effort ... I will test it and report back to you.
