### ISSUE TITLE
Could I use an old GPU - Titian X (maxwell) for train and inference?

### ISSUE THREAD

**Issue by mikegaozheng** [stochasticai/xTuring#227]

**Comment by tushar2407** [comment]
Till you are able to install the library xTuring, and CUDA version is compatible with your GPU, you should not have any problem.

**Comment by mikegaozheng** [comment]
I was trying Titian to train in Int4, it reported  Cuda  Kernerl can not be found.But I passed the cuda and gpu test in Torch

**Comment by StochasticRomanAgeev** [comment]
Hi, @mikegaozheng 
We released new version with fix for this issue and generic int4 enchantment.
In some minutes also will be in pypy.
