### ISSUE TITLE
How to launch?

### ISSUE THREAD

**Issue by basemaly** [stochasticai/xTuring#247]
Apologies for the basic questions, but as I went through the quickstart, I got stuck at the Load Dataset step, and I can't launch the UI. I'm on Windows 11 and when I ran the following in the terminal:
```

>from xturing.datasets import InstructionDataset
'from' is not recognized as an internal or external command,
operable program or batch file.

>Playground().launch()
'Playground' is not recognized as an internal or external command,
operable program or batch file.

>ui.bat

>from xturing.ui.playground import Playground
'from' is not recognized as an internal or external command,
operable program or batch file.

>Playground().launch()
'Playground' is not recognized as an internal or external command,
operable program or batch file.
```
Am I missing a step, or do I need to add xturing to my path or something, even though I'm running it from the xturing directory in the terminal?

**Comment by tushar2407** [comment]
Hi @basemaly , these all are python commands, in order to run this, you first need to enter python environment in your terminal. You can do so by entering the following command on your terminal:
```bash
python
```

**Comment by basemaly** [comment]
It worked. Thank you!
