### ISSUE TITLE
The example pages link in the documentation is not working shows "Not Found"

### ISSUE THREAD

**Issue by AayushSameerShah** [stochasticai/xTuring#256]
This is the examples document page: https://xturing.stochastic.ai/#model-examples

Please try clicking on any of the links, such as for **Llama-2**: https://github.com/stochasticai/xturing/tree/main/examples/llama2

It is not working.
Please fix.

**Comment by StochasticRomanAgeev** [comment]
Fix is done, thanks for pointing out!
Also you can check examples directly in [repo](https://github.com/stochasticai/xTuring/tree/main/docs).
