### ISSUE TITLE
Issue with installing xTuring on Windows

### ISSUE THREAD

**Issue by SwaroopMeher** [stochasticai/xTuring#279]
Issue with installing xTuring on Windows with "pip install xturing"

```
[WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.        
       [WARNING]  unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      DS_BUILD_OPS=1
```

![image](https://github.com/stochasticai/xTuring/assets/115743490/4225dcd0-96d5-4cd1-8af8-8826fe853e05)

![image](https://github.com/stochasticai/xTuring/assets/115743490/ab21176b-611d-4fd5-8f26-8ac30c4c6701)

- OS: Windows 11
- Python 3.11.4
- pytorch_lightning-2.1.3

**Comment by AbrahimZaman360** [comment]
Use conda
