### ISSUE TITLE
Possible to finetune existing GPT2 model?

### ISSUE THREAD

**Issue by wagesj45** [stochasticai/xturing#40]
I have a pre-existing GPT2 model that was fine tuned on a large dataset. I would like to take that model and run it through `xturing` to see how if the instruction capabilities are transfered while still retaining the specialized knowledge/tone from the original fine tuning.

Is it currently possible to use an existing `pytorch_model.bin` and pass it in to `BaseModel.create()`?

**Comment by Toan-Do** [comment]
Hi @wagesj45 , you can pass your weight path to BaseModel.create()

model = BaseModel.create("gpt2_lora", "path/to/your/weight")

or 

model = BaseModel.create("gpt2", "path/to/your/weight")

Please let us know if you need any further information. Thank you.
