### ISSUE TITLE
Fine tune Galactica

### ISSUE THREAD

**Issue by lborcard** [stochasticai/xturing#48]
Great work ! Would it be possible to fine tune Galactica with your tool?

**Comment by Toan-Do** [comment]
Hi @lborcard , thank you for your kind words. We will support other models like Galactica, Flant5, GPTneox, ... and other finetune techniques like int8, int4 finetuning.

Please let us know if you need any further information.

**Comment by lborcard** [comment]
Alright sounds great. I also read that one can use datasets from Huggingface but is it possible to use our own datasets?
