### ISSUE TITLE
How go you save the model ?

### ISSUE THREAD

**Issue by operman18** [stochasticai/xturing#49]
I tried to use the save method but I couldn't load the model afterwards. It seems to work with pickle, but pickle is a pretty bad option which does break depending on the local configuration.

**Comment by Toan-Do** [comment]
Hi @operman18, the saved model is a Pytorch checkpoint, we can load the model using below snip code:

state_dict = torch.load("/path/to/saved/model")
model.load_state_dict(state_dict)

We will add the load method soon. If you need any further information, please let us know. Thank you.

**Comment by operman18** [comment]
Yeah, it does work. I saved the model this way in colab:
`torch.save(model.engine.model.state_dict(),'lora.pt')`

And this how i can load it locally:
`from xturing.models.base import BaseModel
import torch 

model = BaseModel.create('gpt2_lora')

e = torch.load('lora.pt')
m = model.engine.model.load_state_dict(e)
`

**Comment by Toan-Do** [comment]
We're glad to hear it works for you. 

If you need any further information, please let us know. Thank you.
