### ISSUE TITLE
How to load model from saved_model ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [stochasticai/xturing#60]
I have the `saved_model` folder and want to load the `llama_lora` model with the weights i have finetuned.

How to do this ?

**Comment by MarcosRiveraMartinez** [comment]
Hello @MohamedAliRashad,

We have released a new version of the library to simplify the model loading and saving. Could you reinstall the library running the following command?

```bash
pip install xturing --upgrade
```

Now you can load the model as follows:

```python
from xturing import BaseModel

model = BaseModel.load("/path/to/your/directory")

# After this you should be able to run the inference
output = model.generate(texts=["Why are LLM models important"])
```

To load the model in this way, you must have saved your model with the `save` method.

```python
model.save("/path/to/your/directory")
```

You can find some updated guides in our documentation: https://xturing.stochastic.ai/

**Comment by MohamedAliRashad** [comment]
@MarcosRiveraMartinez 

I keep having this error after the upgrade:
```bash
ImportError: cannot import name 'fixed_pos_embedding' from 'transformers.models.gptj.modeling_gptj' 
(/opt/conda/lib/python3.8/site-packages/transformers/models/gptj/modeling_gptj.py)
```

**Comment by Toan-Do** [comment]
Hi @MohamedAliRashad , 

Could you do `pip3 install transformers -U` first? I think that it relates to the version of transformers library. We will add version of libraries in out next release.

**Comment by MohamedAliRashad** [comment]
I fixed the error but now i am facing a new error
```bash
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /shared_volume/rashad/tools/try.py:105 in <module>                                               │
│                                                                                                  │
│   102 # model.engine.model.load_state_dict(state_dict)                                           │
│   103                                                                                            │
│   104 # Perform inference                                                                        │
│ ❱ 105 output = model.generate(texts=["How Egypt can be a Super Power?"])                         │
│   106 print(output)                                                                              │
│   107 # for out in output:                                                                       │
│   108 #     print(f"Generated output after finetuning: {Fore.BLUE}{out}{Style.RESET_ALL}")       │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/xturing/models/causal.py:124 in generate                  │
│                                                                                                  │
│   121 │   │   │   flattened_texts = [texts] if isinstance(texts, str) else texts                 │
│   122 │   │   │                                                                                  │
│   123 │   │   │   outputs.extend(                                                                │
│ ❱ 124 │   │   │   │   self._generate_from_iterable(flattened_texts, do_tokenization=True)        │
│   125 │   │   │   )                                                                              │
│   126 │   │                                                                                      │
│   127 │   │   if dataset is not None:                                                            │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/xturing/models/causal.py:104 in _generate_from_iterable   │
│                                                                                                  │
│   101 │   │   │   │   │   │   input_ids=input_ids, **self.generation_args.dict()                 │
│   102 │   │   │   │   │   )                                                                      │
│   103 │   │   │                                                                                  │
│ ❱ 104 │   │   │   output = self.engine.tokenizer.decode(output[0], skip_special_tokens=False)    │
│   105 │   │   │   outputs.append(output)                                                         │
│   106 │   │                                                                                      │
│   107 │   │   return outputs                                                                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: 'NoneType' object is not subscriptable
```
@MarcosRiveraMartinez @Toan-Do

**Comment by Toan-Do** [comment]
Hi @MohamedAliRashad ,

Thank you for rasing the problem. We have just fixed this problem and plan to release a new version today.

**Comment by Toan-Do** [comment]
Hi @MohamedAliRashad ,

We need to switch to another weight to make loading LLaMA model works on Google Colab because there is no enough RAM if the weight is not sharded into many parts. 

Do not worry, the quality will be not changed.

**Comment by MohamedAliRashad** [comment]
@Toan-Do 
Actually i found the quality better on the new base model :laughing:

**Comment by MohamedAliRashad** [comment]
@Toan-Do 
Those are the insights i found after finetuning the base model `llama_lora`:
1. The GPU VRAM i needed is lower (I needed before 44GB to finetune, Now i was able to train in less thant 20GB)
2. The training time is bigger (In the previous versions It took for a single Epoch an hour, Now it takes an hour and third).
3. The result after the finetuning is worse than before (Now when i ask it a question it keeps repeating and asking different questions similar to it, Previously it would just answer and that's it).

If you have thoughts on why this is happening i would love to hear about it.

**Comment by Toan-Do** [comment]
Hi @MohamedAliRashad 

You are right, we reduce the default batch_size to 1 so the GPU VRAM reduce. You should adjust the batch size which can be fit with your GPU. Check out our doc to see how to change your batch size in the fine-tuning configuration : https://xturing.stochastic.ai/finetune/configure

Using higher batch_size will help to improve the fine-tuning quality. Let us know if it works with you. Thank you.

**Comment by keelezibel** [comment]
Does this library use deepspeed? I was using Lora alone and it took me 9hours to fine tune 7B llama with 2x A100 with 3 epochs.

@MohamedAliRashad based on ur results, it takes an hour or so for an epoch?

**Comment by MohamedAliRashad** [comment]
@keelezibel Yes

**Comment by MohamedAliRashad** [comment]
@Toan-Do Can i finetune LLaMA 13B using xturing ?

**Comment by Toan-Do** [comment]
Hi @keelezibel ,

You can increase your batch size to utilize your gpu memory by changing the fine-tuning configuration. The default batch size is 1 then it might not be optimized in your case. Below is example code in increase the batch size:

`from xturing.models.base import BaseModel
from xturing.datasets.instruction_dataset import InstructionDataset

instruction_dataset = InstructionDataset("alpaca_data")
model = BaseModel.create("llama_lora")

finetuning_config = model.finetuning_config()
finetuning_config.batch_size = 8`

**Comment by Toan-Do** [comment]
Hi @MohamedAliRashad,

We have not supported LLaMA 13B yet. But adding new model/version can be done with only some lines of code. You can follow our instruction to add LLaMA 13B to xTuring : https://xturing.stochastic.ai/contributing/model_contributing

We are welcome if you can make a PR after you are done with it. Thank you.

**Comment by MohamedAliRashad** [comment]
@Toan-Do I have tried multi-gpu training and it was very slow.
Is there something i need to configure in the finetuning method to gain the speed boost ?

**Comment by Toan-Do** [comment]
Hi @MohamedAliRashad, 

Could you please try to increase batch_size:

``from xturing.models.base import BaseModel
from xturing.datasets.instruction_dataset import InstructionDataset

instruction_dataset = InstructionDataset("alpaca_data")
model = BaseModel.create("llama_lora")

finetuning_config = model.finetuning_config()
finetuning_config.batch_size = 8``
