### ISSUE TITLE
How to convert the original weights?

### ISSUE THREAD

**Issue by ch3rn0v** [stochasticai/xturing#83]
Suppose I have a model with the original weights in .pth format.
How do I convert it so that `model = BaseModel.load("path/to/dir")` works properly?
Right now it says: `AssertionError: We were not able to find the xturing.json file in this directory <...>`.
Even if I do convert it to HF format and gain .bin parts, the `xturing.json` file will still be missing.

**Comment by Toan-Do** [comment]
Hi @ch3rn0v,

For loading HF models, you can use below code sample:

```
from xturing.models.base import BaseModel

model = BaseModel.create("cerebras",weights_path="/path/to/a/directory")
```

At the moment, loading from HF models only works with normal models. For LoRA models, there is a small bug for loading HF models. We will fix it soon.

**Comment by ch3rn0v** [comment]
I've installed 0.0.9 release. It still doesn't work.
I tried `model = BaseModel.load(...)`, `model = BaseModel.load_from_local(...)`.

The error remains the same:
`AssertionError: We were not able to find the xturing.json file in this directory`.

The library is only useful to me if it allows for running fine-tuning programmatically. Bonus points if I can test it locally and then pay you to use your cloud computing for upscaling (like 65b model and hundreds of thousands of examples). However right now it just doesn't work. Please tell me what I'm doing wrong. Thank you.

**Comment by Toan-Do** [comment]
Hi @ch3rn0v 

You can not use load method in this case. Please try create method:

```
from xturing.models.base import BaseModel

model = BaseModel.create("llama",weights_path="/path/to/a/directory")
```

or

`model = BaseModel.create("llama_lora",weights_path="/path/to/a/directory")`

Let us know if it works with you.

**Comment by ch3rn0v** [comment]
Thank you for prompt response! Is my understanding correct that `.create` method downloads the raw weights from some source into `weights_path` dir? I'd rather not follow this route as I've already spent time downloading these.

**Comment by Toan-Do** [comment]
Yes it will download and load the default model first then overwrite your model secondly.

**Comment by ch3rn0v** [comment]
Got it, thank you. It's not something I aim for, so I'll keep this as a backup plan.

**Comment by Toan-Do** [comment]
Thank you for your try. We will keep improving xTuring and will improve load/create methods to support more type of models. Let us know if you need any further support.
