### ISSUE TITLE
After Pip Install how can I modify the config file

### ISSUE THREAD

**Issue by samarthsarin** [stochasticai/xturing#86]
I am looking to fine tune the model on my dataset. I used this code

from xturing.datasets.instruction_dataset import InstructionDataset
from xturing.models import BaseModel

instruction_dataset = InstructionDataset("./alpaca_data")
# Initializes the model
model = BaseModel.create("llama_lora_int8")
# Finetuned the model
model.finetune(dataset=instruction_dataset)
# Once the model has been finetuned, you can start doing inferences
output = model.generate(texts=["Why LLM models are becoming so important?"])
print("Generated output by the model: {}".format(output))
# Save the model
model.save("./llama_weights")

But I am looking to change the parameters of the model like number of epochs etc. Can you please guide me how can this be done after I have installed the library using pip.

Thank you

**Comment by StochasticRomanAgeev** [comment]
Hi @samarthsarin,

model.finetuning_config()

Will return you an instance of FinetuningConfig class, which you can modify, and changes will reflect on finetuning process.
(.num_train_epochs is responsible for number of epochs)

**Comment by samarthsarin** [comment]
Thank you.
It worked
