### ISSUE TITLE
Partial training while freezing most of the model/parameters

### ISSUE THREAD

**Issue by Johnreidsilver** [stochasticai/xturing#87]
Is partial training of a few million parameters while freezing the rest of a multi-billion parameter model possible?

**Comment by Johnreidsilver** [comment]
Thanks for the quick reply and tips on low VRAM models.
From a theoretical standpoint do you think it will ever be possible to train only part of the model and leave the rest frozen (and outside of VRAM) ?

**Comment by StochasticRomanAgeev** [comment]
We are already using this approach with LoRA example, most weights are frozen and offloaded to RAM, only when we are interacting with them directly we store them on VRAM.
