### ISSUE TITLE
save trained lora part

### ISSUE THREAD

**Issue by pm-alexander** [stochasticai/xturing#88]
https://github.com/stochasticai/xturing/blob/91ec433b27b8efe9c0a56164b6c103e6f7840bfa/src/xturing/engines/llama_engine.py#L26
It seems like the save is wrong here. if i get it right save_pretrained should be used for the lora's not on the actual model.
The issue currently is that i want to train a lora for llama, but if i run the llama_lora example, i get the whole model saved and not the adapter model itself.
I would expect the adapter to be saved if i run llama_lora.py and the whole model if i run llama.py

**Comment by pm-alexander** [comment]
thanks for the reply
it's actually `model.engine.model.save_pretrained`, if someone wants to save the lora part aswell

**Comment by StochasticRomanAgeev** [comment]
True, thanks for pointing out
