### ISSUE TITLE
Choosing model sizes

### ISSUE THREAD

**Issue by gmonair** [stochasticai/xturing#93]
Hi,

Is there a way to choose the model size? I was looking at the examples in the cerebras folder, and I'd like to experiment with a couple of model sizes, but I can't figure out an easy way to chose what model size gets downloaded.

Thanks!

**Comment by Toan-Do** [comment]
Hi @gmonair ,

The default version is used for Cerebras-GPT model is 1.3B version. If you need to load other variants, you can reference below steps:

1. Download the model or use below commands:

```
git lfs install
git clone https://huggingface.co/cerebras/Cerebras-GPT-6.7B
```

2. Create and load the checkpoint

```
from xturing.models.base import BaseModel

model = BaseModel.create("cerebras",weights_path="/path/to/a/directory")
```

Let us know if it woks with you or you need further information. Thank you.
